# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: iotj.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\niotj.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x1a\n\nphypayload\x12\x0c\n\x04\x64\x61ta\x18\x01 \x03(\x02\"_\n\x04rate\x12\x11\n\tbandwidth\x18\x01 \x01(\x05\x12\x1d\n\nmodulation\x18\x02 \x01(\x0e\x32\t.rate.mod\x12\x14\n\x0cspreadFactor\x18\x07 \x01(\x05\"\x0f\n\x03mod\x12\x08\n\x04LORA\x10\x00\"\x8c\x02\n\x04info\x12\x0f\n\x07\x63hannel\x18\x01 \x01(\x05\x12\x10\n\x08\x63odeRate\x18\x02 \x01(\t\x12\x11\n\tcrcStatus\x18\x03 \x01(\x05\x12\x17\n\x08\x64\x61taRate\x18\x04 \x01(\x0b\x32\x05.rate\x12\x11\n\tfrequency\x18\x05 \x01(\x03\x12\x0f\n\x07loRaSNR\x18\x06 \x01(\x02\x12\x0b\n\x03mac\x18\x07 \x01(\t\x12\x0f\n\x07rfChain\x18\x08 \x01(\x05\x12\x0c\n\x04rssi\x18\t \x01(\x11\x12\x0c\n\x04size\x18\n \x01(\x05\x12(\n\x04time\x18\x0b \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12-\n\ttimestamp\x18\x0c \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"1\n\x04iotj\x12\x12\n\nphyPayload\x18\x01 \x01(\t\x12\x15\n\x06rxinfo\x18\x02 \x01(\x0b\x32\x05.infob\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'iotj_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PHYPAYLOAD._serialized_start=47
  _PHYPAYLOAD._serialized_end=73
  _RATE._serialized_start=75
  _RATE._serialized_end=170
  _RATE_MOD._serialized_start=155
  _RATE_MOD._serialized_end=170
  _INFO._serialized_start=173
  _INFO._serialized_end=441
  _IOTJ._serialized_start=443
  _IOTJ._serialized_end=492
# @@protoc_insertion_point(module_scope)
